### ISSUE TITLE
Saving build history

### ISSUE THREAD

**Issue by BrorSebastianSjovald** [ludwigjo/SE-Gorup10-CI#16]
In order to implement #8, we need a way to store the build history. 

This can be done locally or externally. One way could be that we create a `History/` folder which we store the relevant information in like a `.txt` or `.json` file.

Example:

```json
{
    "commit identifier": "#9e580b9635fae304a09e6e0dd401910b377a7e52", 
    "build date": "2022-02-08 19:05",
    "build logs": {
        "compile log": "example output",
        "test log": "example output 3/4 test failed"
}
```

**Comment by ludwigjo** [comment]
Great idea! Perhaps we can create a method in the Build class introduced in #15 to create his file.
