### ISSUE TITLE
Main method in GitHandler.java

### ISSUE THREAD

**Issue by Sefik-Palazoglu** [ludwigjo/SE-Gorup10-CI#19]
I think we have a main function in one of our classes: GitHandler.java. I assume it was put there for testing it from the comments. But I believe we no longer need it. So we might as well delete it I think.

**Comment by amandakrohn** [comment]
It was in the GitHandler class, so I edited the issue. I agree, since it is not needed it should be deleted.

**Comment by ludwigjo** [comment]
Agree! Will fix
